networks:
  proxy:
    name: studygen
    ipam:
      driver: default
      config:
        - subnet: 192.168.87.0/24

volumes:
  mongodb_data:

services:
  # mongo-setup:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_mongodb
  #   container_name: mongodb-setup
  #   restart: "no"
  #   networks:
  #     - proxy
  #   volumes:
  #     - mongodb_data:/data/db
  #   depends_on:
  #     - mongo1

  mongo1:
    build:
      context: .
      dockerfile: Dockerfile_mongodb
    container_name: mongo1
    hostname: mongo1
    restart: always
    networks:
      - proxy
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
    # command: "mongod --bind_ip_all --replSet=rs0"

  studygen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studygen
    restart: always
    depends_on:
      - mongo1
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - proxy
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      SECRET: ${SECRET}
      # DATABASE_HOST: host.docker.internal
      DATABASE_HOST: mongo1
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MONGODB_SESSION_SECRET: ${MONGODB_SESSION_SECRET}
      SESSION_TTL: ${SESSION_TTL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SECURE_COOKIE: ${SECURE_COOKIE}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      AUTO_INDEX: ${AUTO_INDEX}
    # command: "tail -f dev/null"
